pub mod header;
pub mod footer;
pub mod sidebar;
pub mod console;
pub mod tabs;
pub mod console_panel;
pub mod registers;
pub mod memory;
pub mod assembler;
pub mod io_devices;

pub use header::Header;
pub use footer::Footer;
pub use sidebar::Sidebar;
pub use console::Console;
pub use tabs::{Tabs, TabId};
pub use console_panel::ConsolePanel;
pub use registers::RegistersView;
pub use memory::MemoryView;
pub use assembler::AssemblerView;
pub use io_devices::IoDevicesView;
